config/routes.rb
Wondergem::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  mount Blogit::Engine => "/blog"

  match '/cheat', to:  "static_pages#cheat"   #All About Git
  match '/cheatsheet_install_git', to:  "static_pages#cheatsheet_install_git"  # HOW TO INSTALL GIT
  match '/cheatsheet_repository', to:  "static_pages#cheatsheet_repository"   # HOW TO CREATE  A GIT REPOSITORY
  match '/cheatsheet_clone_a_repository', to:  "static_pages#cheatsheet_clone_a_repository" # HOW TO CLONE A GIT REPOSITORY
  match '/cheatsheet_merge_a_repository', to:  "static_pages#cheatsheet_merge_a_repository"  # CREATE AND MERGE A GIT REPOSITORY 
  match '/cheatsheet_rollback_a_repository', to:  "static_pages#cheatsheet_rollback_a_repository"  # HOW TO ROLLBACK A RESPOSITORY
  match '/cheatsheet_scaffolding', to:  "static_pages#cheatsheet_scaffolding" # SCAFFOLDING BASICS
  match '/cheatsheet_basic_ruby', to:  "static_pages#cheatsheet_basic_ruby" #RUBY BASICS
  match '/cheatsheet_deploying_to_heroku', to:  "static_pages#cheatsheet_deploying_to_heroku"  #DEPLOYING TO HEROKU 
  match '/cheatsheet_rvm_ruby_version_control', to:  "static_pages#cheatsheet_rvm_ruby_version_control"  #RVM: RUBY VERSION CONTROL
  match '/cheatsheet_command_line_basics', to:  "static_pages#cheatsheet_command_line_basics"  #COMMAND LINE BASICS
  match '/cheatsheet_basic_overview_of_testing', to:  "static_pages#cheatsheet_basic_overview_of_testing"  #OVERVIEW OF TESTING  
  
  match '/cheatsheet_smalltalk', to:  "static_pages#cheatsheet_smalltalk"
  
  get "static_pages/help"

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  blogs
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
  def index
    @search = Article.search(params[:search])
    @articles = @search.all   # or @search.relation to lazy load in view
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def cheat
  end
  
  def cheatsheet_repository
  end
  
  def cheatsheet_install_git
  end
  
  def cheatsheet_clone_a_repository 
  end
  
  def cheatsheet_merge_a_repository
  end
  
  def cheatsheet_rollback_a_repository
  end

  def help
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def accordion_block(title, slug, parent, &block)
      content_tag(:div, :class => "accordion-group") do
        head = content_tag(:div, :class => "accordion-heading") do
          link_to(title, "#collapse_#{slug}", :class => "accordion-toggle", :"data-toggle" => "collapse", :"data-parent" => "##{parent}")
        end
        
        body = content_tag(:div, :id => "collapse_#{slug}", :class => "accordion-body collapse") do
          content_tag(:div, :class => "accordion-inner") do
            yield
          end
        end
        head + body
      end
    end
  end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogit/comments/_admin_links.html.erb
<%= login_required(class: "actions") do %>
  <%= link_to(t(:delete, scope: 'blogit.comments'), [@post, comment], method: :delete, confirm: t(:are_you_sure_you_want_to_remove_this_comment, scope: 'blogit.comments')) %>
<% end %>

app/views/blogit/comments/_comment.html.erb
<%= content_tag(:article, id: "blog_comment_#{comment.id}", class: "blog_comment") do %>
  <%= content_tag(:div, class: "blog_comment_name", id: "blog_comment_#{comment.id}_name") do %>
    <%=t :wrote, scope: 'blogit.comments', author: comment.website? ? link_to(comment.name, comment.website) : comment.name %>
  <% end %>


  <%= content_tag(:div, class: "blog_comment_body",
      id: "blog_comment_#{comment.id}_body") do %>
      <%= format_content comment.body || "" %>
  <% end %>

  <%= blog_tag(:footer, type: "comment") do %>
    <%=t :posted_on, scope: 'blogit.comments'%> <%= time_tag(comment.created_at, Blogit.configuration.datetime_format) %>
  <% end %>

  <%= render partial: "blogit/comments/admin_links", locals: {comment: comment} %>

<% end if comment.persisted? %>

app/views/blogit/comments/_form.html.erb
<%= form_for [post, comment], remote: true,
  html: {
    class: "new_blog_comment", id: "new_blog_comment" } do |f| -%>

  <p><%=t :leave_a_comment, scope: 'blogit.comments'%></p>

  <%= field class: "hidden" do %>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
    Hide me using CSS
  <% end %>

  <%= field do %>
    <%= f.label :name, t(:name, scope: 'blogit.comments') %><br>
    <%= f.text_field :name %>
    <%= errors_on(comment, :name) %>
  <% end %>

  <%= field do %>
    <%= f.label :email, t(:email_never_displayed, scope: 'blogit.comments') %><br>
    <%= f.email_field :email %>
    <%= errors_on(comment, :email) %>
  <% end %>

  <%= field do %>
    <%= f.label :website, t(:your_website, scope: 'blogit.comments') %><br>
    <%= f.url_field :website %>
    <%= errors_on(comment, :website) %>
  <% end %>

  <%= field do %>
    <%= f.label :body, t(:your_comment, scope: 'blogit.comments') %><br>
    <%= f.text_area :body %><br>
    <%= errors_on(comment, :body) %>
  <% end %>

  <%= actions do %>
    <%= f.submit t(:add_comment, scope: 'blogit.comments'), :disable_with => t(:adding_comment, scope: 'blogit.comments') %>
  <% end %>
<% end -%>

app/views/blogit/comments/create.js.erb
var $form = $("form#new_blog_comment");
<% if @comment.save %>
  $("#comments").append("<%= escape_javascript(render(@comment)) %>");
  $form.get(0).reset();
<% else %>
  $form.html("<%= escape_javascript(render('form')) %>");
<% end %>

app/views/blogit/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").remove();

app/views/blogit/posts/_active_record_comments.html.erb
<div id="comments">
  <%= render post.comments %>
</div>
<%= render partial: "blogit/comments/form", locals: { post: post, comment: comment } %>

app/views/blogit/posts/_blog_post_spacer.html.erb
<hr class="blog_post_spacer">

app/views/blogit/posts/_empty.html.erb
<div class="blogit_empty_message">
  <%=t :there_are_no_posts_about, scope: 'blogit.posts', tag: params[:tag] %>
</div>

app/views/blogit/posts/_form.html.erb
<%= form_for(@post, html: {class: "new_blog_post", id: "new_blog_post"}) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%=t :prohibited_this_post_from_being_saved, scope: 'blogit.posts', count: @post.errors.count%></h2>

      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= field do %>
      <%= f.text_field :title, placeholder: t(:give_your_post_a_title, scope: 'blogit.posts') %>
    <% end %>

    <%= field do %>
      <%= f.text_area :body, placeholder: t(:write_something_here, scope: 'blogit.posts') %>
    <% end %>
  </fieldset>

  <fieldset>

    <%= field id: "new_blog_post_tag_field" do %>
      <%= f.label :tag_list, t(:tags, scope: 'blogit.posts') %>
      <%= f.text_field :tag_list, placeholder: t(:tag_placeholder, scope: 'blogit.posts') %>
    <% end %>

    <p class="blog_post_tip">
      <%=t :tip_you_can_style_your_post_using, scope: 'blogit.posts', parser: blogit_conf.default_parser %>
    </p>

  </fieldset>

  <%= actions do %>
    <%= f.submit %> <%=t :or, scope: 'blogit.posts'%>
    <%= link_to(t(:cancel, scope: 'blogit.posts'), @post.new_record? ? blog_root_path : post_path(@post)) %>
  <% end %>

<% end %>

app/views/static_pages/cheat.html.erb
<div class="row-fluid">
  <div class="cheat-sheets span12">   
    <div class="span6">
      <h2>Local & Remote Environments</h2>
      <div class="git-map git-one"></div>
    </div> <!-- //end span6  -->
    
    <div class="span6 red-bkgrnd" id="opacity-90">
      <h5>CHEATSHEET:</h5>
      <h2>ALL ABOUT GIT</h2>
      <div class="accordion" id="accordion2">
        <%= accordion_block "What is Git?", "what_is_git", "accordian2" do %>
          <p>
            <span class="strong em"><a href="http://git-scm.com/">Git</a></span> is a distributed open source Version Control System 
            that tracks content such as files and directories. Git allows the creation of a history for a collection of files, 
            and stores the file content in BLOBs (binary large objects); which are captured in states that are fully accessible.
          </p>
          <p>
            The state of a project might be a different collection of files or different content within the files. States can be saved
            as "Branches", which are akin to a copied file.
          </p>  
          <p>
            Since a distributed version control system has no central server, every local copy contains the full history of 
            a project and is stored in a "Commit Object". Every time you make a modification, you have to "Commit" the change.
          </p>
          <p>
            The "Commit File" keeps track of all versions including the author, committer and comments about the updated changes, 
            plus any "Parent" commits that directly precede it allowing to revert back to any point in a project's code history. 
            Git can be used from the command line or terminal.
          </p>
        <% end %>
                             
        <%= accordion_block "What are Repositories?", "what_are_repositories", "accordian2" do %>
          <p><span class="strong em">A repository</span> is a central place where data is stored and maintained for safe keeping. 
            A repository can be a place where multiple databases or files are located for distribution over a network, or a repository 
            can be a location that is directly accessible to the user without having to travel across a network.
          </p>
          <p>The open source community uses repositories to allow software to be found easier and a safe, trusted place to organize projects
            that a team can work with. Repositories can be set up locally; on one's computer or remotely; on a server in the cloud, like 
            Github or Heroku.
          </p> 
        <% end %>
        
        <%= accordion_block "What are Local Repositories?", "what_are_local_repositories", "accordian2" do %>
          <p>
            <span class="strong em">Local repositories</span> are the local copy of a project on one's computer. Using Git allows one to clone or fork
            a repository, e.g. create an exact copy of a repository with a complete history. Owners of repositories can sync changes
            from their local copy to a remote copy by Pulling and Posting; which creates the basic work flow of software development.
          </p> 
        <% end %>
                      
        <%= accordion_block "What are Remote Repositories?", "what_are_remote_repositories", "accordian2" do %>
          <p>
            <span class="strong em">Remote repositories</span> are the remote copy of a project located on another computer or host like Github 
            or Heroku. The "source" repository is often distributed by way of a URL; which describes where the repository is located and what 
            protocol ( http, ssh, git, etc.). 
          </p>
          <p>
            The source is known os the Branch Master and with a series of Git commands, a user will periodically update or "Git Pull" 
            to retrieve new updates
            from the remote repository, then continue working locally and send or "Git Push" new changes or "Commits" to contribute to 
            shared repositories.
          </p>
        <% end %>
        
        <%= accordion_block "What is Github?", "what_is_github", "accordian2" do %>
          <p>
            <span class="strong em"><a href="https://github.com/">Github </a></span>is an open source project that manages and 
            stores revisions of projects. 
            It's literally a Git repository hosting service, with many of it's own features, such as wikis and basic task management tools 
            for every project. The flagship functionality is
            "forking" or copying a repository from one user's account to another; which enables a user to modify a project in a user's own account.
            If you make changes you'd like to share, you can send a notification called a "pull request" to the original owner, then with a 
            click of a button, merge the changes found in your repo with the original repository.
          </p>
          <p>
            It makes contribution management easier allowing for both open-source and private repositories to have a place for
            both development discussions and patch distribution.<br>
            <%= link_to "Create your Github Account Today!", "https://github.com/", :target => "_blank" %>
          </p> 
        <% end %>
        
        <%= accordion_block "What is Heroku?", "what_is_heroku", "accordian2" do %>
          <p>
            <span class="strong em"><a href="http://www.heroku.com/">Heroku</a></span> is a cloud application platform and a brand new way 
            of building and deploying web apps due to it's ease of use. Programmers can spend all of their time in development vs managing servers 
            - a huge win by most accounts.
          </p>
          <p>
            This focus on productivity makes development both easier and painless to build and run cloud applications.
            Designed as an open-source project in Ruby on Rails, the workflow is well documented and works seamlessly with Git.
          </p>
        <% end %>
      </div> <!-- //end accordion2 -->
      
      <div class="btn-group dropup">
        <button class="btn">Next Cheatsheet</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "Command Line Basics", cheatsheet_command_line_basics_path %></li>
          <li><%= link_to "All About Git", cheat_path %></li>
          <li><%= link_to "How to Install Git", cheatsheet_install_git_path %></li>
          <li><%= link_to "How to Create a Git Repository", cheatsheet_repository_path %></li>
          <li><%= link_to "How to Clone Fetch and Pull", cheatsheet_clone_a_repository_path %></li>
          <li><%= link_to "Create and Merge Git Branches", cheatsheet_merge_a_repository_path %></li>
          <li><%= link_to "How to Rollback a Git Repository", cheatsheet_rollback_a_repository_path %></li>
          <li><%= link_to "Deploying to Heroku", cheatsheet_deploying_to_heroku_path %></li>
          <li><%= link_to "RVM: Ruby Version Control", cheatsheet_rvm_ruby_version_control_path %></li>
          <li><%= link_to "Basic Ruby", cheatsheet_basic_ruby_path %></li>
          <li><%= link_to "Scaffolding Basics", cheatsheet_scaffolding_path %></li>
          <li><%= link_to "Overview of Basic Testing", cheatsheet_basic_overview_of_testing_path %></li>
        </ul>
      </div> <!-- //btn-group dropup  -->
      
      <!-- social networks -->
      <div class="canvas">
        <%= link_to "", "https://twitter.com/railsbridge", :id => "twitter", :target => "_blank" %>
        <%= link_to "", "https://github.com/railsbridge", :id => "github", :target => "_blank" %>
      </div>
    </div> <!-- //span5 red-bkgrnd   -->
  </div> <!-- // end cheat-sheets span11   -->
</div> <!-- //end row-fluid -->
  

app/views/static_pages/cheatsheet_basic_overview_of_testing.html.erb
<div class="row-fluid">
  <div class="cheat-sheets span12">   
    <div class="span6">
      <h2>Dummy Copy - Illustration to come</h2>
      <div class="git-map git-one"></div>
    </div> <!-- //end span6  -->
    
    <div class="span6 red-bkgrnd" id="opacity-90">
      <h5>CHEATSHEET:</h5>
      <h2>BASIC OVERVIEW OF TESTING</h2>
      <div class="accordion" id="accordion2">
        <%= accordion_block "What is Git?", "what_is_git", "accordian2" do %>
          <p>
            <a href="http://git-scm.com/">Git</a> is a distributed open source Version Control System that tracks content 
            such as files and directories. Git allows the creation of a history for a collection of files, and stores the 
            file content in BLOBs (binary large objects); which are captured in states that are fully accessible.
          </p>
          <p>
            The state of a project might be a different collection of files or different content within the files. 
            States can be saved as "Branches", which are akin to a copied file.
          </p>  
          <p>
            Since a distributed version control system has no central server, every local copy contains the full history of 
            a project and is stored in a "Commit Object". Every time you make a modification, you have to "Commit" the change.
          </p>
          <p>
            The "Commit File" keeps track of all versions including the author, committer and comments about the updated changes, 
            plus any "Parent" commits that directly precede it allowing to revert back to any point in a project's code history. 
            Git can be used from the command line or terminal.
          </p>
         <% end %>
                       
         <%= accordion_block "What is Github?", "what_is_github", "accordian2" do %>
          <p>
            <a href="https://github.com/">Github </a>is an open source project that manages and stores revisions of projects. 
            It's literally a Git repository hosting service, with many of it's own features, such as wikis and basic 
            task management tools for every project. The flagship functionality is "forking" or copying a repository from one user's 
            account to another; which enables a user to modify a project in a user's own account. If you make changes you'd like to share, 
            you can send a notification called a "pull request" to the original owner, then with a  click of a button, merge the changes 
            found in your repo with the original repository.
          </p>
          <p>It makes contribution management easier allowing for both open-source and private repositories to have a place for
            both development discussions and patch distribution.
          </p> 
        <% end %>
        
        <%= accordion_block "What is Repositories?", "what_is_repositories", "accordian2" do %>
          <p>
            A repository is a central place where data is stored and maintained for safe keeping. A repository can be a place where 
            multiple databases or files are located for distribution over a network, or a repository can be a location that is directly 
            accessible to the user without having to travel across a network.
          </p>
          <p>
            The open source community uses repositories to allow software to be found easier and a safe, trusted place to organize projects
            that a team can work with. Repositories can be set up Locally ( on one's computer ) or Remotely ( on a server in the cloud, 
            like Github or Heroku).
          </p>
        <% end %>
                       
        <%= accordion_block "What are Local Repositories?", "what_are_local_repositories", "accordian2" do %>
          <p>
            Local repositories are the local copy of a project on one's computer. Using Git allows one to clone or fork
            a repository, e.g. create an exact copy of a repository with a complete history. Owners of repositories can sync changes
            from their local copy to a remote copy by Pulling and Posting; which creates the basic work flow of software development.
          </p>
        <% end %>
                
        <%= accordion_block "What are Remote Repositories?", "what_are_remote_repositories", "accordian2" do %>
          <p>
            Remote repositories are the remote copy of a project located on another computer or host like Github or Heroku. 
            The "source" repository is often distributed by way of a URL; which describes where the repository is located and what protocol 
            ( http, ssh, git, etc.). 
          </p>
          <p>
            The source is known os the Branch Master and with a series of Git commands, a user will periodically update or "Git Pull" 
            to retrieve new updates from the remote repository, then continue working locally and send or "Git Push" new changes or "Commits" 
            to contribute to shared repositories.
          </p>
        <% end %>
        
        <%= accordion_block "What is Heroku?", "what_is_heroku", "accordian2" do %>
          <p>
            <a href="http://www.heroku.com/">Heroku</a> is a cloud application platform and a brand new way of building and deploying 
            web apps due to it's ease of use. Programmers can spend all of their time in development vs managing servers 
            - a huge win by most accounts.
          </p>
          <p>
            This focus on productivity makes development both easier and painless to build and run cloud applications.
            Designed as an open-source project in Ruby on Rails, the workflow is well documented and works seamlessly with Git.
          </p>
        <% end %>
      </div> <!-- //end accordion2 -->
      
      <div class="btn-group dropup">
        <button class="btn">Next Cheatsheet</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "Command Line Basics", cheatsheet_command_line_basics_path %></li>
          <li><%= link_to "All About Git", cheat_path %></li>
          <li><%= link_to "How to Install Git", cheatsheet_install_git_path %></li>
          <li><%= link_to "How to Create a Git Repository", cheatsheet_repository_path %></li>
          <li><%= link_to "How to Clone Fetch and Pull", cheatsheet_clone_a_repository_path %></li>
          <li><%= link_to "Create and Merge Git Branches", cheatsheet_merge_a_repository_path %></li>
          <li><%= link_to "How to Rollback a Git Repository", cheatsheet_rollback_a_repository_path %></li>
          <li><%= link_to "Deploying to Heroku", cheatsheet_deploying_to_heroku_path %></li>
          <li><%= link_to "RVM: Ruby Version Control", cheatsheet_rvm_ruby_version_control_path %></li>
          <li><%= link_to "Basic Ruby", cheatsheet_basic_ruby_path %></li>
          <li><%= link_to "Scaffolding Basics", cheatsheet_scaffolding_path %></li>
          <li><%= link_to "Overview of Basic Testing", cheatsheet_basic_overview_of_testing_path %></li>
        </ul>
      </div> <!-- //btn-group dropup  -->
      
      <!-- social networks -->
      <div class="canvas">
        <%= link_to "", "https://twitter.com/railsbridge", :id => "twitter", :target => "_blank" %>
        <%= link_to "", "https://github.com/railsbridge", :id => "github", :target => "_blank" %>
      </div>
    </div> <!-- //span5 red-bkgrnd   -->
  </div> <!-- // end cheat-sheets span11   -->
</div> <!-- //end row-fluid -->

app/views/static_pages/cheatsheet_basic_ruby.html.erb
<div class="row-fluid">
  <div class="cheat-sheets span12">   
    <div class="span6">
      <h2>Dummy Copy - Illustration to come</h2>
      <div class="git-map git-one"></div>
    </div> <!-- //end span6  -->
    
    <div class="span6 red-bkgrnd" id="opacity-90">
      <h5>CHEATSHEET:</h5>
      <h2>BASIC OVERVIEW OF TESTING</h2>
      <div class="accordion" id="accordion2">
        <%= accordion_block "What is Git?", "what_is_git", "accordian2" do %>
          <p>
            <a href="http://git-scm.com/">Git</a> is a distributed open source Version Control System that tracks content 
            such as files and directories. Git allows the creation of a history for a collection of files, and stores the 
            file content in BLOBs (binary large objects); which are captured in states that are fully accessible.
          </p>
          <p>
            The state of a project might be a different collection of files or different content within the files. 
            States can be saved as "Branches", which are akin to a copied file.
          </p>  
          <p>
            Since a distributed version control system has no central server, every local copy contains the full history of 
            a project and is stored in a "Commit Object". Every time you make a modification, you have to "Commit" the change.
          </p>
          <p>
            The "Commit File" keeps track of all versions including the author, committer and comments about the updated changes, 
            plus any "Parent" commits that directly precede it allowing to revert back to any point in a project's code history. 
            Git can be used from the command line or terminal.
          </p>
        <% end %>
                       
        <%= accordion_block "What is Github?", "what_is_github", "accordian2" do %>
          <p>
            <a href="https://github.com/">Github </a>is an open source project that manages and stores revisions of projects. 
            It's literally a Git repository hosting service, with many of it's own features, such as wikis and basic 
            task management tools for every project. The flagship functionality is "forking" or copying a repository from one user's 
            account to another; which enables a user to modify a project in a user's own account. If you make changes you'd like to share, 
            you can send a notification called a "pull request" to the original owner, then with a  click of a button, merge the changes 
            found in your repo with the original repository.
          </p>
          <p>
            It makes contribution management easier allowing for both open-source and private repositories to have a place for
            both development discussions and patch distribution.
          </p> 
        <% end %>
        
        <%= accordion_block "What is Repositories?", "what_is_repositories", "accordian2" do %>
          <p>
            A repository is a central place where data is stored and maintained for safe keeping. A repository can be a place where 
            multiple databases or files are located for distribution over a network, or a repository can be a location that is directly 
            accessible to the user without having to travel across a network.
          </p>
          <p>
            The open source community uses repositories to allow software to be found easier and a safe, trusted place to organize projects
            that a team can work with. Repositories can be set up Locally ( on one's computer ) or Remotely ( on a server in the cloud, 
            like Github or Heroku).
          </p>
        <% end %>
                       
        <%= accordion_block "What are Local Repositories?", "what_are_local_repositories", "accordian2" do %>
          <p>
            Local repositories are the local copy of a project on one's computer. Using Git allows one to clone or fork
            a repository, e.g. create an exact copy of a repository with a complete history. Owners of repositories can sync changes
            from their local copy to a remote copy by Pulling and Posting; which creates the basic work flow of software development.
          </p>
        <% end %>
                
        <%= accordion_block "What are Remote Repositories?", "what_are_remote_repositories", "accordian2" do %>
          <p>
            Remote repositories are the remote copy of a project located on another computer or host like Github or Heroku. 
            The "source" repository is often distributed by way of a URL; which describes where the repository is located and what protocol 
            ( http, ssh, git, etc.). 
          </p>
          <p>
            The source is known os the Branch Master and with a series of Git commands, a user will periodically update or "Git Pull" 
            to retrieve new updates from the remote repository, then continue working locally and send or "Git Push" new changes or "Commits" 
            to contribute to shared repositories.
          </p>
        <% end %>
        
        <%= accordion_block "What is Heroku?", "what_is_heroku", "accordian2" do %>
          <p>
            <a href="http://www.heroku.com/">Heroku</a> is a cloud application platform and a brand new way of building and deploying 
            web apps due to it's ease of use. Programmers can spend all of their time in development vs managing servers 
            - a huge win by most accounts.
          </p>
          <p>
            This focus on productivity makes development both easier and painless to build and run cloud applications.
            Designed as an open-source project in Ruby on Rails, the workflow is well documented and works seamlessly with Git.
          </p>
        <% end %>
      </div> <!-- //end accordion2 -->
      
      <div class="btn-group dropup">
        <button class="btn">Next Cheatsheet</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "Command Line Basics", cheatsheet_command_line_basics_path %></li>
          <li><%= link_to "All About Git", cheat_path %></li>
          <li><%= link_to "How to Install Git", cheatsheet_install_git_path %></li>
          <li><%= link_to "How to Create a Git Repository", cheatsheet_repository_path %></li>
          <li><%= link_to "How to Clone Fetch and Pull", cheatsheet_clone_a_repository_path %></li>
          <li><%= link_to "Create and Merge Git Branches", cheatsheet_merge_a_repository_path %></li>
          <li><%= link_to "How to Rollback a Git Repository", cheatsheet_rollback_a_repository_path %></li>
          <li><%= link_to "Deploying to Heroku", cheatsheet_deploying_to_heroku_path %></li>
          <li><%= link_to "RVM: Ruby Version Control", cheatsheet_rvm_ruby_version_control_path %></li>
          <li><%= link_to "Basic Ruby", cheatsheet_basic_ruby_path %></li>
          <li><%= link_to "Scaffolding Basics", cheatsheet_scaffolding_path %></li>
          <li><%= link_to "Overview of Basic Testing", cheatsheet_basic_overview_of_testing_path %></li>
        </ul>
      </div> <!-- //btn-group dropup  -->
      
      <!-- social networks -->
      <div class="canvas">
        <%= link_to "", "https://twitter.com/railsbridge", :id => "twitter", :target => "_blank" %>
        <%= link_to "", "https://github.com/railsbridge", :id => "github", :target => "_blank" %>
      </div>
    </div> <!-- //span5 red-bkgrnd   -->
  </div> <!-- // end cheat-sheets span11   -->
</div> <!-- //end row-fluid -->